services:
  vnc-server:
    build:
      context: .
      dockerfile: Dockerfile.vnc-server
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ipc: host
    environment:
      - DISPLAY
    command: x11vnc -rfbport 5901 -display $DISPLAY -loop

  no-vnc-client:
    build:
      context: .
      dockerfile: Dockerfile.no-vnc
    ports:
      - 8080:8080
    command: /usr/share/novnc/utils/launch.sh --listen 8080 --vnc vnc-server:5901
