FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get install -y \
        net-tools \
        novnc  && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# CMD /usr/share/novnc/utils/launch.sh --listen 8080 --vnc vnc-server:5900