services:
  remote-desktop:
    build: .
    network_mode: service:husarnet
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ipc: host
    environment:
      - DISPLAY
  
  husarnet:
    image: husarnet/husarnet:2.0.0
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment: 
      - HOSTNAME=my-desktop
      - JOINCODE=${JOINCODE:?you need to create .env file with a JOINCODE variable}
      # - HUSARNET_DEBUG=1