services:
  remote-desktop:
    build: .
    ipc: host
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY
    # ports:
    #   - 9090:9090 # http://ip6-localhost:9090 or http://localhost:9090 or http://my-desktop:9090