services:
  remote-desktop:
    build: .
    ipc: host
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/lib/husarnet
    environment:
      - DISPLAY
      - JOINCODE
      - HOSTNAME=my-desktop
    # ports:
    #   - 9090:9090 # http://ip6-localhost:9090 or http://localhost:9090 or http://my-desktop:9090