# Quick Start
# $ xhost local:root
# $ docker compose -f compose.lan.yaml up -d
# 
# Go to: http://localhost:8080/vnc_auto.html

services:
  remote-desktop:
    image: donowak/remote-desktop:lan
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ipc: host
    ports:
      - 8080:8080
    environment:
      - VNC_PASSWORD=husarion
      - DISPLAY
    command: sleep 3600