# Quick Start
# $ xhost +
# $ docker compose -f compose.vpn.yaml up -d
# 
# Go to: http://my-desktop:8080/vnc_auto.html

services:
  remote-desktop:
    image: donowak/remote-desktop:vpn
    network_mode: service:husarnet
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - VNC_PASSWORD=husarion
      - DISPLAY

  husarnet:
    image: husarnet/husarnet:2.0.0
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment: 
      - HOSTNAME=my-desktop
      - JOINCODE=${JOINCODE:?you need to create .env file with a JOINCODE variable}
      # - HUSARNET_DEBUG=1