# Quick Start
# $ xhost +
# $ docker compose -f compose.test.yaml up -d
# 
# Go to: http://YOUR_HUSARNET_HOSTNAME:8080/vnc_auto.html
# or
# Go to: http://LOCAL_IP_ADDR:8080/vnc_auto.html

services:
  remote-desktop:
    build:
      context: ../
      dockerfile: Dockerfile
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - PASSWORD=husarion
      - DISPLAY