services:
  remote-desktop:
    build: 
      context: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/lib/husarnet
    ipc: host
    ports:
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - DISPLAY=${DISPLAY}
      - HOSTNAME=my-desktop
      - JOINCODE=${HUSARNET_JOINCODE}