name: Build a Docker Image

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: vpn/Dockerfile
            context: vpn/
            docker-tag: vpn
          - dockerfile: lan/Dockerfile
            context: lan/
            docker-tag: lan

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    
    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.dockerfile }}
        platforms: linux/amd64, linux/arm64
        push: true
        tags: dominikn/remote-desktop:${{ matrix.docker-tag }}
        cache-from: type=registry,ref=dominikn/remote-desktop:${{ matrix.docker-tag }} 
        cache-to: type=inline